<?php include "slider.php"; ?>
<?php include "banner.php"; ?>
<?php include "we-work.php"; ?>
<?php include "service.php"; ?>
<?php include "testimoni.php"; ?>
<?php include "team.php"; ?>
<?php include "blog.php"; ?>
<?php include "contact-us.php"; ?>
<?php include "partners.php"; ?>